# Generated by Django 4.1.5 on 2023-01-10 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tags',
            table='tags',
        ),
    ]
